#ifndef _PTHREAD_ERROR_H
#define _PTHREAD_ERROR_H

#include "lsp_common.h"

int		x_pthread_create (pthread_t *thread, const pthread_attr_t *attr, void *(*start_routine) (void*), void *arg, ...); 
inline	void xi_pthread_exit (void *ret_val);
int		x_pthread_join (pthread_t thread, void **ret_val, ...); 
int		x_pthread_tryjoin (pthread_t thread, void **ret_val);
int		x_pthread_timedjoin (pthread_t thread, void **ret_val, const struct timespec *abs_time, ...);
int		x_pthread_detach (pthread_t thread, ...);
inline	pthread_t xi_pthread_self (void);
inline	int	xi_pthread_equal (pthread_t thread_one, pthread_t thread_two); 
int		x_pthread_attr_init (pthread_attr_t *attr, ...); 
int 	x_pthread_attr_destroy (pthread_attr_t *attr, ...);
int 	x_pthread_attr_getdetachstate (pthread_attr_t *attr, int *detachstate, ...); 
int 	x_pthread_attr_setdetachstate (pthread_attr_t *attr, int detachstate, ...);
int 	x_pthread_attr_getguardsize(pthread_attr_t *attr, size_t *guardsize, ...);
int 	x_pthread_attr_setguardsize(pthread_attr_t *attr, size_t guardsize, ...);
int 	x_pthread_attr_getschedparam (pthread_attr_t *attr, const struct sched_param *param, ...);
int 	x_pthread_attr_setschedparam (pthread_attr_t *attr, const struct sched_param *param, ...); 
int 	x_pthread_attr_getschedpolicy (pthread_attr_t *attr, int *policy, ...); 
int 	x_pthread_attr_setschedpolicy (pthread_attr_t *attr, int policy, ...); 
int 	x_pthread_attr_getinheritsched (pthread_attr_t *attr, int *inheritsched, ...);
int 	x_pthread_attr_setinheritsched (pthread_attr_t *attr, int inheritsched, ...); 
int 	x_pthread_attr_getscope (pthread_attr_t *attr, int *scope, ...); 
int 	x_pthread_attr_setscope (pthread_attr_t *attr, int scope, ...);
int 	x_pthread_attr_getstackaddr (pthread_attr_t *attr, void **address, ...); 
int 	x_pthread_attr_setstackaddr (pthread_attr_t *attr, void *address, ...); 
int 	x_pthread_attr_getstack (pthread_attr_t *attr, void *stack_address, size_t stack_size, ...); 
int 	x_pthread_attr_setstack (pthread_attr_t *attr, void **stack_address, size_t *stack, ...); 
int 	x_pthread_attr_getaffinity_np (pthread_attr_t *attr, size_t cpusetsize, const cpu_set_t *cpuset, ...); 
int 	x_pthread_attr_setaffinity_np (pthread_attr_t *attr, size_t cpusetsize, const cpu_set_t *cpuset, ...); 
int 	x_pthread_getattr_default_np (pthread_attr_t *attr, ...); 
int 	x_pthread_setattr_default_np (pthread_attr_t *attr, ...); 
int 	x_pthread_getattr_np (pthread_t thread, pthread_attr_t *attr, ...);
int 	x_pthread_getschedparam (pthread_t thread, int *policy, struct sched_param *param, ...); 
int 	x_pthread_setschedparam (pthread_t thread, int policy, const struct sched_param *param, ...); 
int 	x_pthread_setshcedprio (pthread_t thread, int priority, ...); 
int 	x_pthread_getname_np (pthread_t thread, char *name, size_t len, ...); 
int 	x_pthread_setname_np (pthread_t thread, const char *name, ...); 
int 	x_pthread_getconcurrency (int error_response, ...); 
int 	x_pthread_setconcurrency (int level, ...); 
int 	x_pthread_yield (int error_response, ...); 
int 	x_pthread_setaffinity_np(pthread_t thread, size_t cpusetsize, const cpu_set_t *cpuset, ...); 
int 	x_pthraed_getaffinity_np (pthread_t thread, size_t cpusetsize, cpu_set_t *cpuset, ...);
int 	x_pthread_once (pthread_once_t *once_control, void (*init_routine)(void), ...); 
int 	x_pthread_secancelstate (int state, int *old_state, ...); 
int 	x_pthread_setcanceltype (int type, int *old_type, ...);
int 	x_pthread_cancel (pthread_t thread, ...); 
inline	void xi_pthread_testcancel (void);
int 	x_pthread_mutex_init (pthread_mutex_t *mutex, pthread_mutexattr_t *attr, ...); 
int 	x_pthread_mutex_destroy (pthread_mutex_t *mutex, ...); 
int 	x_pthread_mutex_lock (pthread_mutex_t *mutex, ...);
int 	x_pthread_mutex_trylock (pthread_mutex_t *mutex, ...);
int 	x_pthread_mutex_timedlock (pthread_mutex_t *mutex, const struct timespec *abs_time, ...); 
int 	x_pthread_mutex_unlock (pthread_mutex_t *mutex, ...);
int 	x_pthread_mutex_getprioceiling (const pthread_mutex_t *mutex, int *prioceiling, ...); 
int 	x_pthread_mutex_setprioceiling (pthread_mutex_t *mutex, int prioceiling, int *old_prio_ceiling, ...);
int 	x_pthread_mutex_consistent (pthread_mutex_t *mutex, ...);
int 	x_pthread_mutex_consistent_np (pthread_mutex_t *mutex, ...); 
int 	x_pthread_mutexattr_init (pthread_mutexattr_t *mutex_attr, ...);
int 	x_pthread_mutexattr_destroy (pthread_mutexattr_t *mutex_attr, ...);
int 	x_pthread_mutexattr_getpshared (const pthread_mutexattr_t *mutex_attr, int *pshared, ...); 
int 	x_pthread_mutexattr_setpshared (pthread_mutexattr_t *mutex_attr, int pshared, ...);
int 	x_pthread_mutexattr_gettype (const pthread_mutexattr_t * mutex_attr, int *kind, ...); 
int 	x_pthread_mutexattr_settype (pthread_mutexattr_t *mutex_attr, int kind, ...);
int 	x_pthread_mutexattr_getprotocol (const pthread_mutexattr_t *mutex_attr, int *protocol, ...); 
int 	x_pthread_mutex_setprotocol (pthread_mutexattr_t *mutex_attr, int protocol, ...);
int 	x_pthread_mutexattr_getprioceiling (const pthread_mutexattr_t *mutex_attr, int *prioceiling, ...); 
int 	x_pthread_mutexattr_setprioceiling (pthread_mutexattr_t *mutex_attr, int prioceiling, ...);
int 	x_pthread_mutexattr_getrobust (const pthread_mutexattr_t *mutex_attr, int *robustness, ...);
int 	x_pthread_mutexattr_setrobust (pthread_mutexattr_t *mutex_attr, int robustness, ...);
int 	x_pthread_mutexattr_getrobust_np (const pthread_mutexattr_t *mutex_attr, int *robustness, ...);
int 	x_pthread_mutexattr_setrobust_np (pthread_mutexattr_t *mutex_attr, int robustness, ...); 
int 	x_pthread_rwlock_init (pthread_rwlock_t *rwlock, pthread_rwlockattr_t *attr, ...); 
int 	x_pthread_rwlock_destroy (pthread_rwlock_t *rwlock, ...);
int 	x_pthread_rwlock_rdlock (pthread_rwlock_t *rwlock, ...);
int 	x_pthread_rwlock_tryrdlock (pthread_rwlock_t *rwlock, ...);
int 	x_pthread_rwlock_timedrdlock (pthread_rwlock_t *rwlock, ...);
int 	x_pthread_rwlock_wrlock (pthread_rwlock_t *rwlock, ...);
int 	x_pthread_rwlock_trywrlock (pthread_rwlock_t *rwlock, ...);
int 	x_pthread_rwlock_timedwrlock (pthread_rwlock_t *rwlock, const struct timespec *abs_time, ...);
int 	x_pthread_rwlock_unlock (pthread_rwlock_t *rwlock, ...);
int 	x_pthread_rwlockattr_init (pthread_rwlockattr_t *rwlock, ...); 
int 	x_pthread_rwlockattr_destroy (pthread_rwlockattr_t *rwlock, ...); 
int 	x_pthread_rwlockattr_getpshared (pthread_rwlockattr_t *attr, int *pshared, ...); 
int 	x_pthread_rwlockattr_setpshared (pthread_rwlockattr_t *attr, int pshared, ...); 
int 	x_pthread_rwlockattr_getkind_np (pthread_rwlockattr_t *attr, int *pref, ...); 
int 	x_pthread_rwlockattr_setkind_np (pthread_rwlockattr_t *attr, int pref, ...); 
int 	x_pthread_cond_init (pthread_cond_t *cond, pthread_condattr_t *attr, ...); 
int 	x_pthread_cond_destroy (pthread_cond_t *cond, ...); 
int 	x_pthread_cond_signal (pthread_cond_t *cond, ...); 
int 	x_pthread_cond_broadcast (pthread_cond_t *cond, ...);
int 	x_pthread_cond_wait (pthread_cond_t *cond, pthread_mutex_t *mutex, ...); 
int 	x_pthread_cond_timedwait (pthread_cond_t *cond, pthread_mutex_t *mutex, const struct timespec *abs_time, ...); 
int 	x_pthread_condattr_init (pthread_condattr_t *attr, ...); 
int 	x_pthread_condattr_destroy (pthread_condattr_t *attr, ...); 
int 	x_pthread_condattr_getpshared (pthread_condattr_t *attr, int *pshared, ...); 
int 	x_pthread_condattr_setpshared (pthread_condattr_t *attr, int pshared, ...);
int 	x_pthread_condattr_getclock (pthread_condattr_t *attr, clockid_t *clock_id, ...); 
int 	x_pthread_condattr_setclock (pthread_condattr_t *attr, clockid_t *clock_id, ...);
int 	x_pthread_spin_init (pthread_spinlock_t *lock, int pshared, ...); 
int 	x_pthread_spin_destroy (pthread_spinlock_t *lock, ...); 
int 	x_pthread_spin_lock (pthread_spinlock_t *lock, ...); 
int 	x_pthread_spin_trylock (pthread_spinlock_t *lock, ...); 
int 	x_pthread_spin_unlock (pthread_spinlock_t *lock, ...); 
int 	x_pthread_barrier_init (pthread_barrier_t *barrier, pthread_barrierattr_t *attr, unsigned int count, ...); 
int 	x_pthread_barrier_destroy (pthread_barrier_t *barrier, ...);
int 	x_pthread_barrier_wait (pthread_barrier_t *barrier, ...); 
int 	x_pthread_barrierattr_init (pthread_barrier_t *barrier, ...); 
int 	x_pthread_barrierattr_destroy (pthread_barrier_t *barrier, ...);
int 	x_pthread_barrierattr_getpshared (pthread_barrier_t *barrier, int *pshared, ...); 
int 	x_pthread_barrierattr_setpshared (pthread_barrier_t *barrier, int pshared, ...); 
int 	x_pthread_key_create (pthread_key_t *key, void (*destructor_function) (void*), ...); 
int 	x_pthread_key_delete (pthread_key_t key, ...); 
inline	void *xi_pthread_getspecific (pthread_key_t key, ...); 
int 	x_pthread_setspecific (pthread_key_t key, const void *ptr, ...); 
int 	x_pthread_getcpuclockid (pthread_t thread_id, clockid_t *clock_id, ...); 
int 	x_pthread_atfork (void (*prepare)(void), void (*parent) (void), void (*child)(void), ...); 

#endif /* _PTHREAD_ERROR_H */